server:
   port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    client:
      hostname: localhost

  eureka:
    instance:
      prefer-ip-address: true
      hostname: localhost
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka

